### ISSUE TITLE
Option to add configuration names manually

### ISSUE THREAD

**Issue by gchhablani** [bigscience-workshop/promptsource#106]
I was trying to add templates for `babi_qa` dataset: https://huggingface.co/datasets/babi_qa
This dataset has a conditional-text-generation task that involves multiple types of questions. It has over 20 configurations per set. And it has 8 sets. See [data splits](https://huggingface.co/datasets/babi_qa#data-splits).

However, in the app, only the following configurations appear.
![image](https://user-images.githubusercontent.com/29076344/121132212-7ae89800-c84e-11eb-8d67-f53a7fa942b7.png)

This happens because when the dataset was added, the `dataset_infos.json` was not generated for all configs to keep things light. However, one might want to add configurations that are not present in infos. This can happen for other datasets as well.

Hence, there should be an option to add a custom config name. I'll be adding this in a PR.

**Comment by VictorSanh** [comment]
It seems like there is another level of complexity (`task_no`) that was added solely for BabiQA

<img width="883" alt="Capture d’écran 2021-06-08 à 10 22 31 AM" src="https://user-images.githubusercontent.com/16107619/121202803-95694400-c843-11eb-805f-11520d2e27b3.png">

Can you skip this dataset for now?
For the sake of the prompt sprint, I don't think it's worth working on the app for just one specific dataset. We'll come back to it later if needed

**Comment by gchhablani** [comment]
Yes. This was needed for this dataset due to the number of configurations it allows. I'll skip this one for now.

Thanks @VictorSanh :)
