### ISSUE TITLE
Error in loading proto_qa dataset 

### ISSUE THREAD

**Issue by zaidalyafeai** [bigscience-workshop/promptsource#115]
When attempting to view the `proto_qa` dataset I get the following error 

![image](https://user-images.githubusercontent.com/15667714/121219259-2b28c180-c88c-11eb-80fb-f09956db8fd7.png)

**Comment by VictorSanh** [comment]
Skip for now.
Error on `datasets` side. opened an issue there: https://github.com/huggingface/datasets/issues/2459

**Comment by zaidalyafeai** [comment]
The fix was merged. The error is still there. Maybe need to update from source.

**Comment by stephenbach** [comment]
The cause is that we pinned the version of datasets. @VictorSanh we can upgrade or skip this dataset I guess?

**Comment by zaidalyafeai** [comment]
@stephenbach , already marked a skip for the dataset in the sheet.

**Comment by VictorSanh** [comment]
yes let's skip for now.
we can always be in sync with datasets:master but it's not the priority right now
