### ISSUE TITLE
 FileNotFoundError while loading a dataset

### ISSUE THREAD

**Issue by manandey** [bigscience-workshop/promptsource#13]
Loading datasets like Salesforce/QAConv, wmt/wmt17, yluisfern/PBU etc. failing due to` FileNotFoundError: Couldn't find file locally at Salesforce/QAConv\QAConv.py, or remotely at https://huggingface.co/datasets/Salesforce/QAConv/resolve/main/QAConv.py. Please provide a valid dataset name`

**Comment by arnaudstiegler** [comment]
Looked into that, it's basically coming from the community datasets. Some of them just don't work. 
We could remove those community datasets  by doing `datasets.list_datasets(with_community_datasets=False)` 

I've seen a bunch of issues with those community datasets, like dummy datasets (like `'smallv0221/my-test`) and duplicate datasets (for instance `'lhoestq/squad'`). Not that familiar with that part of the `datasets` hub so not sure how many of the community datasets are valuable.
@stephenbach WDYT?

**Comment by stephenbach** [comment]
Thanks both! Yes, I think focusing on the datasets without community ones is fine for now.

**Comment by arnaudstiegler** [comment]
Sounds good, will open a PR for that
