### ISSUE TITLE
Error in loading definite_pronoun_resolution dataset

### ISSUE THREAD

**Issue by yongzx** [bigscience-workshop/promptsource#188]
![image](https://user-images.githubusercontent.com/29521208/121609736-7ffe4080-ca22-11eb-9c7d-acebf0e1819f.png)

It seems that the data source http://www.hlt.utdallas.edu/~vince/data/emnlp12/train.c.txt is not available.

I have marked "Skip" on the spreadsheet, but I would like to bring this issue to attention.

**Comment by stephenbach** [comment]
Thanks, looks like all of hlt.udallas.edu is down, so maybe someone will fix it soon. 🤞  Leaving open for now so we check again in a day or two.
