### ISSUE TITLE
Example keys with dashes are inaccessible

### ISSUE THREAD

**Issue by stephenbach** [bigscience-workshop/promptsource#20]
Seems to be a quirk of the way we're using Jinja. See, e.g., TREC. A template like
```
{{text}}

Is this asking about a description, an entity, an abbreviation, a person, a quantity, or a location?
|||
{{ ["Description", "Entity", "Abbreviation", "Person", "Quantity", "Location"] [label-coarse] }}
```
doesn't render correctly because `label-coarse` is parsed as `label`. See, e.g., https://stackoverflow.com/questions/28652373/jinja2-in-variable-bug

Can probably just fix by replacing dashes with underscores in keys of the example dictionary when rendering. Might be good to change the displayed information in the sidebar on the fly to match.

**Comment by Urmish** [comment]
I tried pushing a fix to this, but got the following error -
remote: Permission to bigscience-workshop/promptsource.git denied to Urmish

The fix I did was simple. When the template is being saved, I replace all "-" with "_".

![image](https://user-images.githubusercontent.com/9425893/119277829-75047d00-bbe7-11eb-844e-bdc6b20fb6fe.png)

**Comment by stephenbach** [comment]
Thanks for your help with this! I think we might want a different approach, because (at least for me?) this creates a valid Jinja template, but it doesn't actually render the template correctly because there's still a key of "label-coarse" in the dictionary coming from the dataset library. (It renders part of the template, but it doesn't show the answer to the question.) So instead of modifying the templates, I think we need to modify the examples.

**Comment by Urmish** [comment]
Ah! Yes, see if this works?
https://github.com/bigscience-workshop/promptsource/pull/21

Changes both examples and template. I can see the render happening without the label error and the label being displayed -

After the changes -
![image](https://user-images.githubusercontent.com/9425893/119279575-33c59a80-bbf2-11eb-9bbb-15c6af3f015a.png)

Before the changes - 
![image](https://user-images.githubusercontent.com/9425893/119279606-5eafee80-bbf2-11eb-92c3-f1d00b93b98b.png)
