### ISSUE TITLE
`find_undeclared_variables` issue on template

### ISSUE THREAD

**Issue by sbmaruf** [bigscience-workshop/promptsource#216]
Because of this [test](https://github.com/bigscience-workshop/promptsource/blob/main/test/test_templates.py#L50) my pull is failing.

Pull on https://github.com/bigscience-workshop/promptsource/pull/170
There is an unused variable needed to update a dictionary. Otherwise we need `do` extension access. Please see the template, 

```
{% set _ner_label_dict = ({
0:"O",
1:"B-PER",
2:"I-PER",
3:"B-ORG",
4:"I-ORG",
5:"B-LOC",
6:"I-LOC",
7:"B-MISC",
8:"I-MISC"
}) %}
{% set _random_ner_label_dict = ({}) %}
{% for k,v in _ner_label_dict.items() -%}
    {% set _rand_num=range(0, 100) | random %}
    {% if _rand_num > 50 %}
        {% set _dummy = _random_ner_label_dict.update({k:v}) %}
    {% endif %}
{% endfor %}
Generate named entities from the following sentence. The named entities are
{% for k,v in _random_ner_label_dict.items() -%}
    {{ v }}
    {{- ", " if not loop.last else "" -}}
{% endfor %}
{{""}}
{% for i in tokens -%}
    {{- " " if not loop.last else "" -}}
    {{ i }}
{% endfor %}
|||
{%- for tok in tokens -%}
    {%- set outer_loop = loop -%}
    {%- for label in ner_tags -%}
         {%- if outer_loop.index == loop.index -%}
            {{- "" if outer_loop.first else " " -}}
            {%- if label in _random_ner_label_dict -%}
                {{tok}}:{{ _random_ner_label_dict[label] }}
            {%- else -%}
                {{tok}}:O
            {% endif %}
        {%- endif -%}
    {%- endfor -%}
{%- endfor -%}
```
there is no error in the template but it is failing because of the `_dummy` variable.

Pull on https://github.com/bigscience-workshop/promptsource/pull/214
```
 {% if language == "english" %}
{% if annotations.yes_no_answer[0] == "YES" or annotations.yes_no_answer[0] == "NO" %}
{% set _position = ["above", "following"] |choice %}
{% if  _position == "above" %}
Question: {{question_text}}
{{"\n"}}
{% endif %}
Answer the {{_position}} question.
{% if  _position == "following" %}
{{"\n"}}
Question: {{question_text}}
{% endif %}
|||
{{annotations. yes_no_answer[0]}}
{% endif %}
{% endif %}
```

The variable `_position` is detected as unused variable. Not sure why. But there is no error in the template. Because of this issue it is not passing the test.

Any workaround to solve the issue?

**Comment by gchhablani** [comment]
I checked #214. Here, you need to define _blank2 on top of all your Jinja, outside the if conditions. Inside the if conditions, you can update but not create a new variable. I faced a similar issue on some PR.

A PR where the same thing happened: https://github.com/bigscience-workshop/promptsource/pull/168

**Comment by yongzx** [comment]
The problem is that you have defined set these variables inside an if-else block.

```
{% if _rand_num > 50 %}
    {% set _dummy = _random_ner_label_dict.update({k:v}) %}
{% endif %}
```

This is the same issue that I have encountered for my PR: #223 .

**Comment by sbmaruf** [comment]
Thanks @yongzx  @gchhablani . It solves the issue.
