### ISSUE TITLE
[open for discussion] `get_dataset` for bigger datasets (downloading bottleneck)

### ISSUE THREAD

**Issue by VictorSanh** [bigscience-workshop/promptsource#23]
Dumping here for discussion

When you query a new dataset, the datasets library downloads it (there is no way to look at a subset of the data without downloading it entirely), which becomes a bottleneck if 1/ you want to write prompts for bigger datasets, 2/ you write prompts for a lot of datasets.

To smooth as much as possible the prompt sourcing, a possibility to consider is to set up a unique (big) server with the app running on it with all the necessary datasets already loaded/downloaded.
 
This would also simplify the sync between multiple people (no need to push PRs on Github) but we would be compromising on the traceability...
How would we ensure "quality" though (for instance: grammaticality, understanding of the task, etc.)?

**Comment by stephenbach** [comment]
We'd need to add some handling of simultaneous users anyway, so maybe each user gets their own sandbox somehow that saves their version of templates.yaml. Then we periodically merge them in to github via some review process?

**Comment by tianjianjiang** [comment]
I haven't done this in quite a while but perhaps a Streamlit server that saves files to another (or even this) git repo with user branches? (Kinda like when we write a paper in LaTeX and sync to one git repo)

**Comment by VictorSanh** [comment]
Sorry, I am so late to answer...

I added a [spreadsheet](https://docs.google.com/spreadsheets/d/10SBt96nXutB49H52PV2Lvne7F1NvVr_WZLXD8_Z0JMw/edit?usp=sharing) with the identified datasets and column "who prompts it". That should solve the conflicts of multiple people working on the same datasets if we say that one dataset is assigned to one person and one only (at least in a 1st pass)

But I agree that we should have some review process and it seems that having it through the PRs seems like the easiest way to do so.
We should even break down the `templates.yaml` by dataset so that it's easier to track and to merge.
