### ISSUE TITLE
Write Template Writing Guide

### ISSUE THREAD

**Issue by stephenbach** [bigscience-workshop/promptsource#26]
There should be some guidelines for users. For now, we can assume they are BigScience participants, so the technical details of using the system are less important. It's more about what kind of information should be included in prompts, pitfalls to avoid, and other tips (i.e., how to map labels to strings in a way consistent with few-shot evaluation techniques).

**Comment by VictorSanh** [comment]
+ add a step before submitting for code quality/style:

> **4. Format your code.** Run black and isort so that your newly added files look nice with the following command:
> ```bash
> make style
> make quality
> ```
