### ISSUE TITLE
Priority dataset disappears from dataset list after adding a third template

### ISSUE THREAD

**Issue by elsanns** [bigscience-workshop/promptsource#27]
1. Select `Filter Priority Dataset`
2. Select a dataset with 2 templates (e.g.: ag_news)
3. Type in a new template name, press `Create`
4. The form refreshes and the current dataset no longer appears in the template list (because of the `count_dict[d]>2` condition)

One possible solution would be to save the name of the current working dataset and include it in the
templates list in `list_datasets`, something like:
`        dataset_list = list(set(dataset_list) - 
        set(list(d for d in count_dict if count_dict[d]>2 and d!=state.current_dataset_name))) `

When should it be cleared? Maybe as soon as the new template has been saved?

**Comment by manandey** [comment]
Hi @elsanns, since you will be submitting a PR for this, will it be possible to include a input field/ dropdown with a list of values like [5,10,15,20] to get a user-defined value for the number of existing templates to filter the dataset list?

**Comment by elsanns** [comment]
Hi @manandey,
Yes, I will add a field for that, the value will be used instead of the fixed threshold of 2 templates per dataset, good idea
