### ISSUE TITLE
Datasets which requires manual download failing to load with object has no attribute 'keys' error

### ISSUE THREAD

**Issue by manandey** [bigscience-workshop/promptsource#33]
I think we need to handle the datasets which require manual download (https://huggingface.co/docs/datasets/loading_datasets.html#manually-downloading-files). eg. msr_zhen_translation_parity, hippocorpus, msr_genomics_kbcomp etc.

**Comment by VictorSanh** [comment]
Yes, for the moment, I think we can simply skip the datasets that require manual construction/download (such as C4 for instance).

If you have already identified some of them, would you mind tagging them here in [this list](https://docs.google.com/spreadsheets/d/10SBt96nXutB49H52PV2Lvne7F1NvVr_WZLXD8_Z0JMw/edit?usp=sharing) in the comments column?

**Comment by manandey** [comment]
Sure, I will update the list in the spreadsheet.

**Comment by VictorSanh** [comment]
Added an explicit flag in [this commit](https://github.com/bigscience-workshop/promptsource/commit/2c76bc06fcdacd66cebbece2a3a831b1aa75f466#diff-1401cba615c695ccf5e53b264a6269f9a823a03cd00fdf2120d5117e00850326)
