### ISSUE TITLE
Prompt filters

### ISSUE THREAD

**Issue by srush** [bigscience-workshop/promptsource#4]
Some prompts may only apply to a subset of the data. (For instance datasets with multiple languages.) Maybe an optional filter function per prompt.

**Comment by VictorSanh** [comment]
Closing it since it is adressed

**Comment by stephenbach** [comment]
Reopening since this might not have been resolved. I think the proposal is to have optional user-written functions that determine whether an example is converted to a prompt or skipped.

@srush do you have a preferred format? Seems like Jinja could work here too, e.g.,
```
{{ label == 0}}
```
?

**Comment by srush** [comment]
Yeah, I think just ignoring strings where  `str.strip() == False` solves my problems in a convenient manner. This probably doesn't even need to be included in the tool, just the docs.
