### ISSUE TITLE
Dataset Schema getting displayed twice

### ISSUE THREAD

**Issue by manandey** [bigscience-workshop/promptsource#40]
![image](https://user-images.githubusercontent.com/6687858/120213721-2d1dcf80-c251-11eb-8193-23fb6ace210e.png)

**Comment by manandey** [comment]
Should I submit a PR for this @stephenbach ?

**Comment by stephenbach** [comment]
Thanks, will look now. Good chance it's related to #21

**Comment by stephenbach** [comment]
@manandey Sure, if you've got the fix. Thanks!

**Comment by stephenbach** [comment]
Yeah, lines 217--218 are just duplicates that should be deleted.
