### ISSUE TITLE
Rank eval of vanilla D4

### ISSUE THREAD

**Issue by awebson** [bigscience-workshop/promptsource#456]
Since Colin is using the TPUs exclusively for training, @VictorSanh would you please use Jean Zay to evaluate the vanilla D4 checkpoints instead of other ablations? You don't have evaluate all checkpoints, maybe schedule them such that, 1/2 steps checkpoint first, then 1/4 and 3/4 steps checkpoints, then 1/5, 2/5, 3/5, 4/5 checkpoints, and so on…

Also, if ReCoRD is slow to eval we should skip it. Seqio doesn't currently handle multiple correct answers so we need to run their official eval script anyway. Let me know if there are other datasets that are unusually slow to eval.

**Comment by VictorSanh** [comment]
yes, will schedule intermediate checkpoints
