### ISSUE TITLE
Writing: Broader Impacts Section

### ISSUE THREAD

**Issue by srush** [bigscience-workshop/promptsource#459]

**Comment by srush** [comment]
Keeping track that @StellaAthena is looking into this.

**Comment by craffel** [comment]
We should finish this ASAP, ideally, so that we can have the social impact WG take a look.

**Comment by StellaAthena** [comment]
I am currently waiting on training statistics from @VictorSanh to do carbon/energy analysis.

I can put a proposal for bias analysis before the Social Impact WG tonight or tomorrow, though I won't be avaliable tomorrow to respond to questions.

What were people thinking of including under the "Social impact" heading that isn't those two categories?

**Comment by craffel** [comment]
Carbon/energy analysis is done - no need to worry about that. If you can work on the bias piece before tomorrow, that's great. Not sure if this falls under bias, but it seems like it could be pertinent to include some discussion of dual-use, etc. But I wasn't thinking of anything outside of that.

**Comment by VictorSanh** [comment]
> I am currently waiting on training statistics from @VictorSanh to do carbon/energy analysis.

@StellaAthena, fwiw, I shared with you the statistics on slack a few hours ago, did you receive it?

**Comment by StellaAthena** [comment]
> > I am currently waiting on training statistics from @VictorSanh to do carbon/energy analysis.
> 
> @StellaAthena, fwiw, I shared with you the statistics on slack a few hours ago, did you receive it?

Oh, I didn't get a notification. Weird.

@craffel Gotcha.
