### ISSUE TITLE
Writing: Adding cites for papers we took prompts from in generated prompt appendix. 

### ISSUE THREAD

**Issue by srush** [bigscience-workshop/promptsource#461]
We need to list all of the paper that we took prompts from in the appendix. I think these are in the yaml, but they are not clean. Someone needs to go through and pull them out.

**Comment by VictorSanh** [comment]
Did a spreadsheet [here](https://docs.google.com/spreadsheets/d/1tk5mUT7-Az5SbW7J6h7aSsKRO6XATV5vaasUTejShEU/edit?usp=sharing).
The `\cite ref` corresponds to the bibtext entries in the latex (I added the additional ones under `supplementary.bib`)

**Comment by VictorSanh** [comment]
let me know if you need more

**Comment by srush** [comment]
beautiful, thanks.
