### ISSUE TITLE
More-than-one-OG prompt ablation

### ISSUE THREAD

**Issue by craffel** [bigscience-workshop/promptsource#465]
We currently have one ablation where we only train the model on one OG prompt per dataset. We can do an additional ablation where we train it on M OG prompts and N non-OG prompts. There have been various proposals for the values of M and N. I suggested we set M to the largest possible value for each dataset (i.e. however many OG prompts have been proposed) and N to zero. This would allow us to measure the benefit of including non-OG prompts. Other proposals have been fixed values for M, N, e.g. (3, 1). Let's decide now and run it.

@VictorSanh 
@awebson 
@srush 
@stephenbach

**Comment by VictorSanh** [comment]
After giving it much thought, I am also in favor of setting M to max, and N to 0.
Looking at the results, it seems like training on a lot of prompts to see good generalization. So the more prompts/datasets the better.
In this sense D4+GPT only OG templates sounds like the right ablation to do.

**Comment by craffel** [comment]
PR #468

**Comment by craffel** [comment]
This is running now.
