### ISSUE TITLE
Run on Big Bench

### ISSUE THREAD

**Issue by craffel** [bigscience-workshop/promptsource#469]

**Comment by VictorSanh** [comment]
👀 @StellaAthena and @lintangsutawika

**Comment by craffel** [comment]
@lintangsutawika 's owning this and hopes to get results in the next 24h.

**Comment by lintangsutawika** [comment]
Sample result.

[novel_concepts_finetune-t5-xxl-lm-d4-all-091621.json.zip](https://github.com/bigscience-workshop/promptsource/files/7252426/novel_concepts_finetune-t5-xxl-lm-d4-all-091621.json.zip)

Others are still running. I had a few hours of troubleshooting that was solved by downgrading the pytorch version I was using.

**Comment by craffel** [comment]
Awesome! Do they provide an automated way of getting scores out?

**Comment by lintangsutawika** [comment]
Yes, the evaluate_task.py pretty much does the heavy lifting. My work mostly covered adapting the T5 to the model codebase that basically has two types of prediction: generation and multiple choice.

**Comment by craffel** [comment]
Ok, great. Eager to see the scores once inference finishes on all the tasks.

**Comment by StellaAthena** [comment]
Great work!

**Comment by srush** [comment]
wild, @lintangsutawika I can help get these into graph form. let me know when you settle on a format.

**Comment by lintangsutawika** [comment]
@srush Will keep you posted! @VictorSanh and I are splitting the load.

**Comment by srush** [comment]
@lintangsutawika said the numbers are here: gs://bigscience/experiment_d/bigbench/finetune-t5-xxl-lm-d4-091621-512/1-112-200/output I'll try to extract both to pandas this evening.

**Comment by VictorSanh** [comment]
> @lintangsutawika said the numbers are here: gs://bigscience/experiment_d/bigbench/finetune-t5-xxl-lm-d4-091621-512/1-112-200/output I'll try to extract both to pandas this evening.

yup it's pointing to the same thing. `language_identification` is still running, and it's very hard to say when it's going to finish, I'll upload it though when it's done

**Comment by VictorSanh** [comment]
we've got all of them on the bucket!

**Comment by VictorSanh** [comment]
Evals
- [X] D4
- [ ] D4+GPT - RUNNING
- [ ] D4+GPT+SGlue - RUNNING

**Comment by VictorSanh** [comment]
We are starting to have the results for D4+GPT and D4+GPT+SGlue. I added the links.
