### ISSUE TITLE
Writing: Fix Splits figure

### ISSUE THREAD

**Issue by srush** [bigscience-workshop/promptsource#470]
@yongzx  is working on this .

**Comment by yongzx** [comment]
Version 1
[T0 Datasets.drawio.pdf](https://github.com/bigscience-workshop/promptsource/files/7245601/T0.Datasets.drawio.pdf)

Things to do:
- [ ] Needs to trim white spaces in PDF export file. 
- [ ] On the same note, make it wider by taking advantage of the fact that we have more width than height.
- [ ] align the bigger boxes across the side? (QA extractive with QA extractive)

**Comment by srush** [comment]
A couple changes from the spreadsheet (these were my fault): 

- [ ] QQP and MRPC should be on the train side too. 
- [ ] ReCoRD should be on the extractive eval side.
- [ ] OpenBook QA  should be multiple choice
- [ ] QASC is multiple choice
- [ ] Social I QA should be on both sides
- [ ] MultiRC is multiple choice
- [ ] Wiqa is multiple choice

**Comment by yongzx** [comment]
@srush ReCoRD should be moved from Coreference to QA Extractive, or do I keep the "Record" in coreference?

**Comment by srush** [comment]
@awebson any thoughts on record? It seems to be QA extractive in the table.

**Comment by srush** [comment]
Also It looks like we have a lot of room wide. So I think 4 columns is the way to go (2 for train, 2 for eval. )

**Comment by awebson** [comment]
Let's keep ReCoRD as extractive QA. I will explain in the paper how there is ambiguity on whether it (and quoref) can also be considered as coreference.

Also, in the spreadsheet I wrote "QA extractive",  "QA multiple-choice" for sorting purposes. In the paper and figures, we should write "Extractive QA", "Multiple-Choice QA", etc. to be easier to read.

Lastly, is it possible to avoid having dataset rectangles that are twice the size of others? I know it's hard to fit the names, but it gives a false impression of the dataset is larger or somehow more important. Maybe increase size of all rectangles, or if really necessary use abbreviations like "Adv. QA".

**Comment by yongzx** [comment]
@srush @awebson how about this? 
[T0 Datasets-2.drawio (1).pdf](https://github.com/bigscience-workshop/promptsource/files/7269673/T0.Datasets-2.drawio.1.pdf)

**Comment by srush** [comment]
This looks pretty good to me! Let me see how it looks in the paper.

The colors may not be necessary. Can you send a version as well with all white and only nli with a color?

**Comment by yongzx** [comment]
Here you go! 

[T0 Datasets-3.drawio.pdf](https://github.com/bigscience-workshop/promptsource/files/7269781/T0.Datasets-3.drawio.pdf)

- [X] remove colors except NLI in eval.
