### ISSUE TITLE
Writing: Results, Discussion, and Heavy Editing Throughout

### ISSUE THREAD

**Issue by awebson** [bigscience-workshop/promptsource#475]
Technically I only own the Benchmarking, Results, and Discussion sections, but forgive me that I will also heavily edit/rewrite the other sections for a coherent narrative (blame @epavlick for our obsession with writing.) I have already done a first pass of edits of the below, but will incrementally update them throughout the week:

- [x] 1 Introduction
- [x] 2 Related Work
- [x] 3 Measuring Generalization to New Tasks (formerly Benchmarking Multitask Generalization)
- [x] 4 A Unified Prompt Format (formerly From Datasets to Prompted Examples)
- [ ] 5 Experimental Setup (leaving the model subsection to @craffel)
- [ ] 6 Results
- [ ] 7 Discussion

For non-first-authors too: Feel free to make Overleaf comments or reply to comments I made. But please don't resolve any comments unless you're @srush. Unlike Google Doc, resolved comments in Overleaf are mysteriously sorted and kinda hard to find. Also, don't do what I do in short comments like "revisit" or "rephrase". Please explain why they need to be revisited or why the phrasing is confusing or insufficient.

If you find a typo/grammatical error, feel free to directly overwrite it. If you have stylistic phrasing or substantive changes, please either use Overleaf comment or turn on Track Changes.

**Comment by srush** [comment]
Awesome! Thanks for looking it over.

**Comment by srush** [comment]
@awebson if you are planning on continuing doing large rewriting changes, can you give me a timeline? I only have limited time on Monday, and the deadline early Tuesday. Would very much like to have a complete draft that you are happy with asap.

**Comment by yongzx** [comment]
Is there a way for me to add comments? I don't see the "Review" button for me. My Overleaf account is zheng_xin_yong@brown.edu

**Comment by stephenbach** [comment]
Overleaf invite sent!

**Comment by awebson** [comment]
@srush Terribly sorry for the delay! Was occupied by result analysis and fixing metrics. 

I promise to finish sections 3 and 4 tomorrow. And to ease you worries a bit, unlike what I did to Intro and Related Work, edits to S4 will be mostly stylistic not substantive.
