### ISSUE TITLE
Bias/fairness quantitative measurements

### ISSUE THREAD

**Issue by VictorSanh** [bigscience-workshop/promptsource#477]
Two goals:
- have quantitative measurements for the paper's Broader impact section
- reflect these in the model cards when we release checkpoints

4 held out evaluation sets identified by the Evaluation WG:
- jigsaw_toxicity_pred
- crows_pairs
- winogender (AXG in SuperGLUE)
- winobias

At the current state, I see
`crows_pairs` and `winobias` prompted, `jigsaw_toxicity_pred` has an opened PR (#451) we need to check, `winogender` needs to be prompted.

Workflow:
- [x] prompt those that were not prompted yet
- [x] making sure these were actually cached (@VictorSanh can have this caching step done fairly quickly)
- [x] evaluation (normal and score rank evaluation) or maybe they have some special evaluation?
- [x] when we know which checkpoints exactly to eval, get the final numbers to report

**Comment by VictorSanh** [comment]
@StellaAthena

**Comment by awebson** [comment]
Pasted from Slack discussion for reference:

> currently in HF datasets https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge/data ; what the Eval WG proposed https://www.kaggle.com/c/jigsaw-unintended-bias-in-toxicity-classification

The former might have been added to our dataset spreadsheet while the latter just got added to HF. Still, I get a download error for both though.

Also, Winogender and Winobias can use the prompts from Winogrande.

**Comment by StellaAthena** [comment]
@awebson I am able to download both from Kaggle without issue.

> Also, Winogender and Winobias can use the prompts from Winogrande.

It looks like crow pairs is the only one that needs prompting then. I can take care of that today.

**Comment by StellaAthena** [comment]
Actually, it looks like [crows-pairs](https://github.com/bigscience-workshop/promptsource/blob/main/promptsource/templates/crows_pairs/templates.yaml) has a template already.

**Comment by Iwontbecreative** [comment]
> Pasted from Slack discussion for reference:
> 
> > currently in HF datasets https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge/data ; what the Eval WG proposed https://www.kaggle.com/c/jigsaw-unintended-bias-in-toxicity-classification
> 
> The former might have been added to our dataset spreadsheet while the latter just got added to HF. Still, I get a download error for both though.

Yes, I added jigsaw_unintended_unintended to datasets since we were going to need it. Is your error related to the manual download required for the dataset? If yes, I think that is expected since the data is obtained through kaggle rather than direct download.

**Comment by stephenbach** [comment]
Working on a PR for winogender/winobias copying from winogrande.

**Comment by VictorSanh** [comment]
@Iwontbecreative just reviewed your PR, sorry we only getting back to it now

**Comment by awebson** [comment]
@stephenbach: 
> to clarify, we already have some (I think) nice templates for wino_bias
> Did you want them to be replaced with the winogrande ones, have winogrande ones added in, or leave alone?
Sorry for the late reply. This is a judgment call. On the one hand, we want to test the biases of the same coreference prompts we use for the non-bias-measuring evals (i.e., SuperGLUE WSC.fixed and Winogrande XL), but I don't want to dismiss what others have already written so far. So best to do a union. 

Except I'd reject coreference prompts that:
- Include a hardcoded example in the template itself. That makes it no longer a zero-shot. 
- Use jargons like “coreference” or even “referent”. Most non-linguists have no idea what they mean. We prefer non-jargon like “what does x refer to”. See my examples in super_glue wsc.fixed.

@debajyotidatta would you please open a PR as soon as possible with prompts from your working group?

**Comment by stephenbach** [comment]
Whoops, wsc273 has nothing to do with this issue. Can't seem to remove the mentions above, but disregard please.

**Comment by stephenbach** [comment]
Current status of 4 datasets:

- jigsaw_toxicity_pred #451 open, changes made, needs re-review
- crows_pairs: #442 merged a while ago
- winogender: #482 open, needs review (minor changes)
- winobias: #488  open, needs review

**Comment by debajyotidatta** [comment]
Hi @stephenbach @VictorSanh @awebson : We still have not been able to reach a consensus about the prompts from the social bias working group. I do not think our discussions will be over until we meet a few more times, so we should just go ahead with the prompts that are already there for these datasets and when we are ready we will open a PR.

**Comment by stephenbach** [comment]
Ok, thanks for letting us know!

**Comment by VictorSanh** [comment]
Results are starting to come in as I am parsing the results.
For T0:
```bash
super_glue/axg/super_glue_axg_GPT_3_style_score_eval - 0.848314606741573
super_glue/axg/super_glue_axg_MNLI_crowdsource_score_eval - 0.8342696629213483
super_glue/axg/super_glue_axg_based_on_the_previous_passage_score_eval - 0.851123595505618
super_glue/axg/super_glue_axg_can_we_infer_score_eval - 0.8370786516853933
super_glue/axg/super_glue_axg_does_it_follow_that_score_eval - 0.8230337078651685
super_glue/axg/super_glue_axg_does_this_imply_score_eval - 0.8679775280898876
super_glue/axg/super_glue_axg_guaranteed_true_score_eval - 0.8567415730337079
super_glue/axg/super_glue_axg_justified_in_saying_score_eval - 0.8258426966292135
super_glue/axg/super_glue_axg_must_be_true_score_eval - 0.8567415730337079
super_glue/axg/super_glue_axg_should_assume_score_eval - 0.8230337078651685
```

**Comment by StellaAthena** [comment]
I shot the winogender authors an email asking if they had code.

**Comment by VictorSanh** [comment]
Closing for now as these made their way to the paper and model card. will re-open an issue with potential revisits when we need them
