### ISSUE TITLE
Add some dummy checks to the jinja template

### ISSUE THREAD

**Issue by VictorSanh** [bigscience-workshop/promptsource#48]
Add a suite of sanity checks on the jinja template. for instance,
- are all variables called in the template actual keys in the example dictionary?
- template content is a duplicated with another one

Please add ideas!

+ can duplicate these tests into the "common pitfalls" section of the contribution guide (#26)

**Comment by tianjianjiang** [comment]
> are all variables called in the template actual keys in the example dictionary?
I was trying to find a way of augmenting an jinja template without altering its variables. If this one can have variables actually separated, it could be really helpful.
