### ISSUE TITLE
parse or annotate Jinja template | before augmentation → augmenters know where the off-limit variables are

### ISSUE THREAD

**Issue by tianjianjiang** [bigscience-workshop/promptsource#49]
related: #10 #48 

One of the quick'n'dirty ways that I imagine comprises the 4 steps below:
1. Get the variable list of a template string
```python
parsed_content = env.parse(template_string)
variable_list = meta.find_undeclared_variables(parsed_content)
```
2. Send `parsed_content` and `variable_list` to an augmenter
3. An augmenter replace variables with some special tokens that its algorithm won't touch (to some extent)
4. After augmentation, put variables back to where they were

**Comment by stephenbach** [comment]
Thanks! Here's an example I've been playing with:

```
{{text}} 
Is this a piece of news regarding world politics, sports, business, science and technology? ||| 
{{ ["World politics", "Sports", "Business", "Science and technology"][label] }}
```

An issue is that important information might not be expressed as variables. (For example, the dataset schema doesn't always provide the most natural name for each category, see, e.g., TREC. So how could we update this template?

One option is to just single braces or something and parse them out when rendering:
```
{{text}} 
Is this a piece of news regarding {world politics, sports, business, science and technology}? ||| 
{{ ["World politics", "Sports", "Business", "Science and technology"][label] }}
```

Another, which I think is probably not good, is to define all "important" stuff as variables:
```
{% set labels = ["World politics", "Sports", "Business", "Science and technology"] %}
{{text}} 
Is this a piece of news regarding {{ labels[0].lower() }}, {{ labels[1].lower() }}, {{ labels[2].lower() }}, or {{ labels[3].lower() }}? ||| 
{{ labels[label] }}
```
but that seems cumbersome. How would this example look in the process you're thinking of @tianjianjiang ?

**Comment by tianjianjiang** [comment]
@stephenbach Thank you for the nice examples, exactly what I was considering!
Assuming the author of an augmentation algorithm has almost full control of the outcome, e.g., I know that back-translation can be tricked with arbitrary tokens such as HTML tags or just X, Y, Z.
For example-1,
```
{{text}} 
Is this a piece of news regarding {world politics, sports, business, science and technology}? ||| 
{{ ["World politics", "Sports", "Business", "Science and technology"][label] }}
```
I may change it to
```
xxx1
Is this a piece of news regarding xxx2 ? yyy
```
before sending it to the augmenter.

A similar setting can happen for example-2 and yet we may or may not need some more Jinja code for `(% ... %}`

Of course if an augmentation algorithm doesn't really process the whole text, e.g., just altering some words with synonyms, then we probably don't need the special treatment of replacing with tricky token anyway.

**Comment by stephenbach** [comment]
Gotcha, that makes sense. So viewing this from the perspective of what constraints do we need to enforce from the beginning, we should figure out what the lightest weight addition is that leaves options open for augmentation. Curly braces are lightweight, but it gets a little messy if we want to add escaping so someone can use a curly brace as actual punctuation in the template. If we think curly braces are essential punctuation and don't want to add too much processing, we could also do things like
```
{{ ["world politics, sports, business, science and technology"][0] }}
```
and then just parse out all the Jinja control code.

Do folks have preferences?

**Comment by stephenbach** [comment]
Current proposal on the table is to wrap anything that is protected in Jinja. For literal text, we can just do
```
Here's some text that can be modified. {{"Here's some text that can't."}}
```
I think it's a fine solution. More sophisticated code for generating text will thus be protected (and possibly handled specially) as well.

**Comment by tianjianjiang** [comment]
Pardon me for nudging @srush @shanyas10 @abheesht17 here for the above questions from @stephenbach .
I think you guys are also interested in this topic and #55.

**Comment by stephenbach** [comment]
Also would benefit from your opinion @tianjianjiang 🙂 This proposal is currently what’s in the template writing guide (#51 ). As long as this seems sufficient to address the concerns you raised about leaving the door open for different augmentation strategies, I think we’re all good.

**Comment by VictorSanh** [comment]
The solution of wrapping anything that is protected in Jinja looks good to me and it answers both the constraints for the augmentation and for writing prompts (simple enough).
Let's go with this solution
