### ISSUE TITLE
Couldn't find a directory or a dataset named 'story_cloze'

### ISSUE THREAD

**Issue by bwang482** [bigscience-workshop/promptsource#492]
```
MacOS Big Sur 11.6
Python 3.7.11
Streamlit, version 0.88.0
```
Earlier I had issue https://github.com/bigscience-workshop/promptsource/issues/489 with the interface and I think it has been resolved now following https://github.com/bigscience-workshop/promptsource/pull/411

Now I get this error below while downloading: 

```
FileNotFoundError: Couldn't find a directory or a dataset named 'story_cloze'. It doesn't exist locally at /Users/bowang/Code/promptsource/story_cloze or remotely at https://raw.githubusercontent.com/huggingface/datasets/1.12.1/datasets/story_cloze/story_cloze.py
Traceback:
File "/Users/bowang/opt/anaconda3/envs/hug/lib/python3.7/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
File "/Users/bowang/Code/promptsource/promptsource/promptsource.py", line 120, in <module>
    infos = get_dataset_infos(dataset_name)
File "/Users/bowang/opt/anaconda3/envs/hug/lib/python3.7/site-packages/datasets/inspect.py", line 113, in get_dataset_infos
    module_path, _ = prepare_module(path)
File "/Users/bowang/opt/anaconda3/envs/hug/lib/python3.7/site-packages/datasets/load.py", line 528, in prepare_module
    f"Couldn't find a directory or a {resource_type} named '{path}'. "
```

Is this a known issue? Do I need to manually add something?

**Comment by tianjianjiang** [comment]
> Is this a known issue? Do I need to manually add something?

I'm not sure whether it is a well-known issue, but my guess is that you will have to manually download it because the remote feature isn't done according to https://github.com/huggingface/datasets/pull/2907

+CC @zaidalyafeai

**Comment by bwang482** [comment]
Thanks @tianjianjiang 

I am not sure I can download it since it's not in HF datasets. Why is it included in promptsource then? @zaidalyafeai

**Comment by zaidalyafeai** [comment]
@bwang482, story_cloze  was important for evaluation so we had to include it even though it is not originally in hfds (there is a [PR ](https://github.com/huggingface/datasets/pull/2907)for it). It is a special case because it is not public (acquired through email).

**Comment by tianjianjiang** [comment]
As @zaidalyafeai aforementioned, story_cloze is crucial for the paper and I suppose that info was only announced during the meeting and probably somewhere in the slac channel.

IMO it is safe to ignore hat error for now, especially when the rest of streamlit should work, iirc.
