### ISSUE TITLE
[Promptsource] custom/community datasets

### ISSUE THREAD

**Issue by VictorSanh** [bigscience-workshop/promptsource#503]
Fix that (i think it's related to the datasets that we add while they were not merged into datasets' master yet)
<img width="1489" alt="Capture d’écran 2021-10-06 à 12 25 31 PM" src="https://user-images.githubusercontent.com/16107619/136244645-325e550c-93e2-4d1d-944a-50cd1737eb6a.png">

**Comment by stephenbach** [comment]
Claiming this. Yeah, we need a different way to handle this. On my todos.

**Comment by stephenbach** [comment]
Should be fixed by #498.
