### ISSUE TITLE
Remove `do_train` and `do_evals` from templates

### ISSUE THREAD

**Issue by VictorSanh** [bigscience-workshop/promptsource#505]
<img width="466" alt="Capture d’écran 2021-10-07 à 5 31 11 PM" src="https://user-images.githubusercontent.com/16107619/136465089-39bf8ebb-795f-4c62-9e9b-afdbb73fa9c5.png">

We are not using these anymore

**Comment by zaidalyafeai** [comment]
I am looping over all the templates, then loading using `yaml` and overwriting the yaml  file with a new one that has the two fields removed. Is this the best approach ?

**Comment by stephenbach** [comment]
I think anything that results in a diff of only those two lines per template removed is good. I don’t think there are any references to those outside the yaml, but please double check.

**Comment by zaidalyafeai** [comment]
I can't find them anywhere except in the `yaml` files. My first approach of using `yaml` loader doesn't work because there are some custom tags. This simple approach seems to work. I can check all the templates manually to make sure that only those two lines changes. 

``` python
   lines = open(template_path, 'r').readlines()
    new_lines = []
    for line in lines:
        if '_do_eval' in line or '_do_train' in line:
            continue
        else:
            new_lines.append(line)
    file = open(f, 'w').write(''.join(new_lines))
```

**Comment by zaidalyafeai** [comment]
I submitted a PR https://github.com/bigscience-workshop/promptsource/pull/518
