### ISSUE TITLE
Fix rendering: use simple `st.text` instead of `st.markdown`

### ISSUE THREAD

**Issue by VictorSanh** [bigscience-workshop/promptsource#511]
The rendering is messed up in a bunch of places.
A few issues that are symptomatic: #355 #326

Replace `st.markdown` by `st.text` and extensively test that the rendering is better.

**Comment by zaidalyafeai** [comment]
I suffered from this one and I want to resolve it :)

**Comment by zaidalyafeai** [comment]
regarding `_` we can escape it `t.replace("_","\\_")` to solve the problem. 

before 
![image](https://user-images.githubusercontent.com/15667714/136693883-6cdbabaa-1fee-41ab-841b-01ced5dc55b2.png)

after 

![image](https://user-images.githubusercontent.com/15667714/136693861-f634e79b-28f9-4f77-b462-6329be21a0af.png)

There are also other especial characters that we need to take care of https://discuss.streamlit.io/t/how-to-sanitize-user-input-for-markdown/828/4

```python
def escape_markdown(text):
    MD_SPECIAL_CHARS = "\`*_{}[]()#+-.!"
    for char in MD_SPECIAL_CHARS:
        text = text.replace(char, "\\"+char)
    return text
```

**Comment by stephenbach** [comment]
Perhaps it's best just to display as plain text with st.text?

**Comment by VictorSanh** [comment]
Yes i would advocate to drop the highlighting (st.text doesn't display any fancy markdown related formatting anyway) unless @zaidalyafeai you feel VERY VERY confident about these highlight inserts (and the fact that they don't mess up anything)

**Comment by zaidalyafeai** [comment]
@VictorSanh I was referring to special characters that might appear as part of the input text (X) not the prompt ( I am not sure if this causes problems as well or not). I agree that fixing the issues is more important than the visual stuff.

**Comment by stephenbach** [comment]
#532 is merged.
