### ISSUE TITLE
Pin version of promptsource

### ISSUE THREAD

**Issue by VictorSanh** [bigscience-workshop/promptsource#515]
Once everything is ready for release, pin the version of `promptsource`

**Comment by tianjianjiang** [comment]
May I suggest we also pin `python~=3.7.1` (or even 3.7.12) to avoid multiprocessing issues on macOS and Windows?

**Comment by VictorSanh** [comment]
> May I suggest we also pin `python~=3.7.1` (or even 3.7.12) to avoid multiprocessing issues on macOS and Windows?

Could you expand on the multiprocessing bug you are running into on mac os and windows? The only place where we are using it (unless there is some stuff happening under streamlit) is here:
https://github.com/bigscience-workshop/promptsource/blob/e3b2202be6c0c67c4ee01803c96c5cba9ea5a846/promptsource/promptsource.py#L103

any suggestion on how to fix that? i'd like to avoid pinning the python version

**Comment by tianjianjiang** [comment]
> @VictorSanh I will try it again with #411 and see whether it will be compatible with python3.8 on both macOS and Windows (and certain streamlit version).

After a test I recall that we will have to fix #416 (`'NoneType' object has no attribute 'session_id'`), otherwise python3.8 won't work.
