### ISSUE TITLE
Hosted Streamlit app showing "Unrecognized RootContainer in deltaPath:" error

### ISSUE THREAD

**Issue by dvsrepo** [bigscience-workshop/promptsource#560]
Hi 👋 

This effort is amazing! Congrats.

I've tried to browse the hosted version but I get the following error (URL: http://34.88.112.77:8501/):

<img width="1536" alt="Screenshot 2021-10-20 at 10 46 51" src="https://user-images.githubusercontent.com/1107111/138060425-09d01346-177b-485c-a7bb-04807258784d.png">

I'm using Brave (although it seems it's a server error)

Apologies if this is not the right place to report this.

**Comment by dvsrepo** [comment]
Now it's working even on Brave, thanks! Feel free to close this issue

**Comment by VictorSanh** [comment]
@dvsrepo there are a couple of bugs (some of them are streamlit related) that I am seeing at scale (on the hosted version) but not on local versions... Generally, refreshing the page helps, but we should fix these at some point...

**Comment by mpomarole** [comment]
It seems like the hosted version is also down: http://34.88.112.77:8501/. This is the link on the root README.

**Comment by VictorSanh** [comment]
> It seems like the hosted version is also down: http://34.88.112.77:8501/. This is the link on the root README.

Could you share a screenshot of what's not working @mpomarole? the [hosted version](bigscience.huggingface.co/promptsource) is working for me

**Comment by zaidalyafeai** [comment]
Works for me as well.

**Comment by mpomarole** [comment]
Wasn't working when I posted, now it is.
