### ISSUE TITLE
Change `v0.1` in prompt reference to a more descriptive comment/link

### ISSUE THREAD

**Issue by VictorSanh** [bigscience-workshop/promptsource#643]
Multiple prompts have `v0.1` as a commen in the reference field. Change it to `Sanh et al. 2021` for instance (or at least something that other people than ourselves can understand)

**Comment by zaidalyafeai** [comment]
I can work on this.

**Comment by zaidalyafeai** [comment]
https://github.com/bigscience-workshop/promptsource/pull/692
