### ISSUE TITLE
Template checking fails for datasets that require additional imports

### ISSUE THREAD

**Issue by stephenbach** [bigscience-workshop/promptsource#66]
We are creating a dataset builder to get the features. While we can do this without downloading the data, `datasets.load.prepare_module` can try to import things that are not necessarily installed, causing the automated tests to crash.

Example: https://github.com/bigscience-workshop/promptsource/pull/63/checks?check_run_id=2747124281

Options:
1) Skip tests on such datasets
2) Add needed dependencies to `requirements.txt` as they arise.
3) Find a way to get the features without using `prepare_module`

Thoughts?

**Comment by VictorSanh** [comment]
I am in favor of 2 even though we'll have to be quite careful of not introducing version conflicts...

I can ask around for 3.

**Comment by stephenbach** [comment]
Ok, will go with 2. I'll list everything added in this way in a commented section in case we want to take them back out at some point. Will leave this open in case anyone has an idea for 3.

**Comment by stephenbach** [comment]
Closing for now. We've still only hit this once for `samsum`.
