### ISSUE TITLE
Scripts For Evaluating T0 with Prompts

### ISSUE THREAD

**Issue by gabeorlanski** [bigscience-workshop/promptsource#661]
Hello, are there publicly available scripts for how the evaluation was done for the fixed choice tasks in the [T0 Paper](https://arxiv.org/pdf/2110.08207.pdf)? 

I tried implementing them myself but have been getting different results for the log probability ranking and wanted to verify that I implemented it correctly. If the scripts are not publicly available, are there any instructions and/or similar projects that have a similar implementation?

**Comment by VictorSanh** [comment]
Hi @gabeorlanski  
Our training and evaluation codebase is mainly based on the t5 codebase (https://github.com/google-research/text-to-text-transfer-transformer). For the bigbench numbers, we relied on the original bigbench repository (mainly converting the checkpoints to pt format)

**Comment by VictorSanh** [comment]
@gabeorlanski here are the official scripts to reproduce the main results: https://github.com/bigscience-workshop/t-zero -> section "Evaluation"
