### ISSUE TITLE
Training Code for T0*?

### ISSUE THREAD

**Issue by reppertj** [bigscience-workshop/promptsource#662]
I'm trying to understand what it would take to reproduce some of the fine-tuning results in the paper -- I see the checkpoint (pytorch) weights are on HF hub, but is the training code publicly available anywhere?

Thanks!

**Comment by VictorSanh** [comment]
Hi @reppertj 
Our training and evaluation codebase is mainly based on the t5 codebase (https://github.com/google-research/text-to-text-transfer-transformer). We then converted the trained checkpoints to pt to release them on the hub. I am happy to provide the tf checkpoints too if that's helpful.

**Comment by reppertj** [comment]
Thanks, @VictorSanh! Yes, the TF checkpoints would absolutely be helpful.

**Comment by reppertj** [comment]
Thanks, @VictorSanh!  Closing this issue.
