### ISSUE TITLE
Expanding promptsource to other languages

### ISSUE THREAD

**Issue by shakedbr** [bigscience-workshop/promptsource#686]
Hi,

I'm working on a contribution of prompts that are code related, such as:
1. Given a docstring and/or a function name, generate the function body.
2. Given a function body, generate a function name.
3. Given a function call f(…) generate the return value.
4. Given a code with <masked> tokens, retrieve them, given several choices.
5. Given a buggy code (e.g. wrong identifier, wrong operator), classify whether there is
a bug.
6. Given a buggy code, detect the bug location.
7. Given a buggy line, fix the line
...

Currently, promptsource is limited to English datasets only: [https://github.com/bigscience-workshop/promptsource/blob/2940f27f7fa5a228ecb72f8e5f2807524a33adf2/promptsource/utils.py#L124](https://github.com/bigscience-workshop/promptsource/blob/2940f27f7fa5a228ecb72f8e5f2807524a33adf2/promptsource/utils.py#L124)

While there are some code-related datasets that pass this filter (e.g. `openai_humaneval` and `great_code`), I would be happy if I can work on more datasets.

My questions are:
1. Are you planning to extend the tool for other languages, namely, removing this filter or relaxing it, so the community will be able to contribute prompts to non-English datasets.
2. Are you interested in code-related prompts like I mentioned above?

Thanks!

**Comment by VictorSanh** [comment]
Great to hear that you are interested in these topics @shakedbr !

to answer your questions:
1/ We have been discussing this and have considered a few options for the best strategy to extend promptsource (or even whether we need to extend) to multiple languages. The rationale is that modifying the logic for languages requires some broad changes to the tool and sends a strong signal. At the moment, we think that we don't have enough evidence onto what is the best modeling strategy:
- machine-translate English prompts into language X and apply them to datasets in language X (code-switching setup)
- machine-translate English prompted instances into language X
- write prompts in language X for datasets in English
- write prompts in language X for datasets in language X
- etc.
Choosing requires experimental results that we don't have yet.
2/ yes, we welcome that type of contributions!

**Comment by shakedbr** [comment]
Great, thanks!

**Comment by thesofakillers** [comment]
Hi @VictorSanh, just some questions regarding PromptSource in other languages:

- I don't see what is wrong with just letting contributions be made in these languages. Is this just a moderation issue?
- By "modifying the logic for languages", do you mean modifying (appropriately translating/adapting) the templates for each incoming new language? Wouldn't this be handled by incoming contributors?
- Regarding the pending experimental results you mention, are these currently being worked on? Would love to give a hand or have insight into updates

Thanks!
Giulio
