### ISSUE TITLE
Download and Export P3 dataset to jsonl format

### ISSUE THREAD

**Issue by sbmaruf** [bigscience-workshop/promptsource#687]
In a recent discussion at architecture and scaling WG, it was asked if we can convert p3 dataset into raw json format.

I am not sure if the conversion script should be here or not. But in case if we want to keep such script in this repository, I can send a PR here. 

Current implementation, 
```
https://github.com/sbmaruf/p3-dataset-json-dump
```

**Comment by VictorSanh** [comment]
I am leaning towards putting it somewhere else. What would be the rationale for putting it here?

**Comment by sbmaruf** [comment]
When I see the current structure of this project I cannot see any place where we can put this code.
But this place could be discussion point to where we can open a pull request. I am hoping once we have >=13B Multilingual Model, we would do the multi-task training with P3 dataset. But I'm not sure where should I open a pull request.

**Comment by VictorSanh** [comment]
how about opening a PR here: https://github.com/bigscience-workshop/t-zero
