### ISSUE TITLE
manual download logic

### ISSUE THREAD

**Issue by VictorSanh** [bigscience-workshop/promptsource#693]
We need a logic to specify a local path for datasets that require manual download in particular to support the bio med group.

What I am imaginating:
when `manual_download_required` is detected in the call to `load_dataset`, then a text box/input box appears on the interface to give the user the ability to give a local path, then re-run load_dataset with this `data_dir`

**Comment by thomasw21** [comment]
I think that ideally we should still be able to run `load_dataset("story_cloze", "2016")` without specifying that data dir. I think this requires changes in the `datasets` library, where we'd somehow be able to cache a manually downloaded dataset. Typically the flow would be:
 - manually download a dataset
 - cache the dataset in arrow format using something along the lines of `prepare("story_cloze","2016", data_dir={DATA_DIR})`
 - and then be able to load `load_dataset("story_cloze", "2016")`
 
 I'm yet to figure if this is possible/wanted?
 
 The other simple way is to allow one to set a flag `PROMPTSOURCE_MANUAL_DATASET_DIR` where we'd store all the custom datasets one needs and where we'd run the following snipet to load a dataset.
 
 ```python
 try:
    ds = load_dataset("story_cloze", "2016")
 except ManualDownloadError as e:
    ds = load_dataset("story_cloze", "2016", os.environ["PROMPTSOURCE_MANUAL_DATASET_DIR"])
 ```

**Comment by VictorSanh** [comment]
> Typically the flow would be:
> 
> * manually download a dataset
> * cache the dataset in arrow format using something along the lines of `prepare("story_cloze","2016", data_dir={DATA_DIR})`
> * and then be able to load `load_dataset("story_cloze", "2016")`

I am not sure I am following. Calling `load_dataset("story_cloze", "2016", data_dir=<your_fav_path>)` caches the dataset in an arrow format and the exact path (from what I understand) is determined by the `data_dir`.
So I am not sure I see the difference between `prepare("story_cloze","2016", data_dir={DATA_DIR})` and `load_dataset("story_cloze","2016", data_dir={DATA_DIR})`...

I like the `PROMPTSOURCE_MANUAL_DATASET_DIR` env variable though. Instead of another text box popping up, it would raise an error message if we couldn't find the dataset subfolder in `os.environ["PROMPTSOURCE_MANUAL_DATASET_DIR"]`

**Comment by thomasw21** [comment]
The idea is you only need to `prepare` once, and then use `load_dataset` without `data_dir` as the notion of having manually downloaded the data or not disapears.

I can open a PR for the flag.

**Comment by VictorSanh** [comment]
i might be missing something but it seems like a naming convention. with datasets that don't require manual download, `load_dataset` still downloads and cache it the first time, and then it's still name `load_dataset`. for datasets that require manual download, you download and put it in `data_dir` once, cache it once and then the call to the function doesn't change.

Unless I am totally missing something, let's use what you suggested: `load_dataset("story_cloze", "2016", f'{os.environ["PROMPTSOURCE_MANUAL_DATASET_DIR"]}/story_cloze')`

**Comment by VictorSanh** [comment]
for the record, I was confused but Thomas explained it to me: #708 handles two shortcomings with previously had
- the UX flow for datasets that require manual download
- the fact that we needed to manually change the arguments of load_dataset when task caching with seqio

👀 @jason-fries we now support a smooth workflow for datasets that require manual downloads (basically downloading them under `~/.cache/promptsource`)
