### ISSUE TITLE
Jinja sometimes splits in the `Prompted dataset viewer`

### ISSUE THREAD

**Issue by VictorSanh** [bigscience-workshop/promptsource#694]
Figure out why this happens and open a PR to fix it

Some examples:
<img width="969" alt="Capture d’écran 2021-12-07 à 4 41 30 PM" src="https://user-images.githubusercontent.com/16107619/145869838-b0f7408d-45b3-4720-9b4a-85ca45269dbe.png">
<img width="1425" alt="Capture d’écran 2021-12-08 à 5 22 16 PM" src="https://user-images.githubusercontent.com/16107619/145869846-5d8d1716-406e-4455-9a42-e6e8393ffbf6.png">

**Comment by zaidalyafeai** [comment]
Seems to be caused by multiple new lines.

**Comment by VictorSanh** [comment]
yes, that sounds like the right diagnostic
would you like to propose a fix for that @zaidalyafeai ?

**Comment by zaidalyafeai** [comment]
Using `re.sub(r'\n+', '\n', t)` inside `show_jinja` function seems to resolve the issue. Not sure why `{% for candidate in
candidate_answers -%}` is not in one line, though. Did we have this problem before?

![image](https://user-images.githubusercontent.com/15667714/146334849-397f1889-1063-49ec-92b4-c97aca04a656.png)

**Comment by zaidalyafeai** [comment]
@VictorSanh, If that is ok, I can submit a PR today. Won't be able to work on it later, because I am traveling.

**Comment by VictorSanh** [comment]
I'd like the rendering to be as faithful as the template (i.e. if there are 3 \n then we should display 3 \n). Would doing a `join` before calling https://github.com/bigscience-workshop/promptsource/blob/415a49333f792a52b682ece4ef107082b015a6ea/promptsource/app.py#L91 solve the issue?
