### ISSUE TITLE
Transfer `promptsource.seqio_tasks` to https://github.com/bigscience-workshop/t-zero

### ISSUE THREAD

**Issue by VictorSanh** [bigscience-workshop/promptsource#703]
Separate promptsource from the tooling specific to the T0 paper

**Comment by VictorSanh** [comment]
also change the mixture name to something self-explanatory....

**Comment by thomasw21** [comment]
Unrelated to the move exactly, but I think we should mention somewhere that running with `HF_DATASETS_OFFLINE=1` saves a lot of time when importing those tasks:

```
> DATASETS_VERBOSITY=error time -p python3 -c "from promptsource import seqio_tasks"
real 199.22
user 36.44
sys 14.02
> HF_DATASETS_OFFLINE=1 DATASETS_VERBOSITY=error time -p python3 -c "from promptsource import seqio_tasks"
real 8.17
user 10.51
sys 12.72
```

This holds true even if one doesn't actually use the datasets and has already cache the tasks.
