### ISSUE TITLE
glue/mrpc prompt returns empty

### ISSUE THREAD

**Issue by jpilaul** [bigscience-workshop/promptsource#722]
@dimapihtar and I have ran into an issue that we are not able to fix. We are applying the prompt template on glue's mrpc data we get an empty results

To replicate:
input
```python
{
'sentence1': "Yucaipa owned Dominick 's before selling the chain to Safeway in 1998 for $ 2.5 billion .", 
'sentence2': "Yucaipa bought Dominick 's in 1995 for $ 693 million and sold it to Safeway for $ 1.8 billion in 1998 .", 'label': 0, 'idx': 1
}
```
output
```python
['']
```

**Comment by VictorSanh** [comment]
Hi @jpilaul 
could you give a lil' more details (for instance by providing a snippet of code)?
in particular, I am interested in which prompt of glue/mrpc you are using.

**Comment by dimapihtar** [comment]
@VictorSanh
Trying to apply existing prompt for each example of dataset:
`def apply_prompts(data, prompts, name):
    prompts_lst = prompts.all_template_names
    counter = 0
    for example in data:
        for index, prompt in enumerate(prompts_lst):
            print(counter, prompt, example)
            result = prompts[prompt].apply(example)
            row = {'src': name, 'text': '{context} {completion}'.format(context=result[0], completion=result[1]), 'type': 'Eng'}`
Getting an **IndexError** when prompt was not applied (empty list "result")
Seems like it fails only on not original task prompts. Tried this assumption for mrpc and paws (labeled_final) data and script fails when I'm trying to apply not original prompt.

**Comment by VictorSanh** [comment]
Yes this is expected, the templates you are trying to apply are conditionally based on the label. It means that it will skip some of the examples. In the case of glue/mrpc/generate_paraphrase, the example will be skipped when the label is 0, which eventually will return a "blank" prompted example.

<img width="433" alt="Capture d’écran 2022-01-27 à 10 18 48 PM" src="https://user-images.githubusercontent.com/16107619/151481600-f89f87db-6dce-4bf3-bbc5-dc8da6d2fbad.png">
 
Here's a minimal code to see it:
```python
from datasets import Dataset, load_dataset
from promptsource.templates import DatasetTemplates

data = load_dataset("glue", "mrpc", split="train")
ex = data[1]
assert ex["label"] == 0

prompts = DatasetTemplates("glue/mrpc")
p = prompts["generate_paraphrase"]

result = p.apply(ex)
assert result == [""]
```

Such examples are flagged as "blank result" in the "prompted dataset viewer".

**Comment by VictorSanh** [comment]
i am closing this for now. feel free to re-open if something is not clear!
