### ISSUE TITLE
PyPi install issue

### ISSUE THREAD

**Issue by Guitaricet** [bigscience-workshop/promptsource#726]
Executing `pip install promptsource` causes the following error for me

```
    ERROR: Command errored out with exit status 1:
     command: /home/vlialin/miniconda3/envs/cqg/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-higkq2vp/promptsource_d9e0de5b5f404523afa2d8789946c6a8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-higkq2vp/promptsource_d9e0de5b5f404523afa2d8789946c6a8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qnu5er_g
         cwd: /tmp/pip-install-higkq2vp/promptsource_d9e0de5b5f404523afa2d8789946c6a8/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-higkq2vp/promptsource_d9e0de5b5f404523afa2d8789946c6a8/setup.py", line 6, in <module>
        with open('requirements.txt') as requirements_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
```

I was trying to understand what is a possible problem, but this one is confusing, because the previous line `with open("README.md", "r", encoding="utf-8") as readme_file:` also reads a local file and it does not fail.

I will make a PR that removes `requirements.txt` in favor of explicitly providing a list of dependencies to `install_requires`.

**Comment by Guitaricet** [comment]
The PR: https://github.com/bigscience-workshop/promptsource/pull/727

**Comment by awebson** [comment]
Thanks Vlad! @stephenbach would you mind taking a look at this? I'm not sure if it's related but right now I can't even `pip install promptsource` on an empty Colab.

```
WARNING: Discarding https://files.pythonhosted.org/packages/b7/e1/4b05573af2c2d3901d0a7e78dd604a8ef756d7a74cdf4573246779f6ed6d/promptsource-0.2.0.tar.gz#sha256=e96effb6e49e5b6f9d817eb259382c3a3db2eb1e950b8d797056a6898205b4b7 (from https://pypi.org/simple/promptsource/) (requires-python:>=3.7, <3.8). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement promptsource (from versions: 0.2.0)
ERROR: No matching distribution found for promptsource
```

**Comment by awebson** [comment]
FWIW, I did `!python --version` and Colab currently has 3.7.12.

I'm not sure why we require 3.7 aside from the fact that the readme says “for stability reasons”.

**Comment by VictorSanh** [comment]
We pinned to Python3.7 (in this [commit](https://github.com/bigscience-workshop/promptsource/commit/9b91d27d50d0f82bce6922156240a1e3a1510ba0)) for various rendering bugs reasons (see https://github.com/bigscience-workshop/promptsource/issues/416, https://github.com/bigscience-workshop/promptsource/pull/385, https://github.com/bigscience-workshop/promptsource/pull/444).

Removing this constraint (https://github.com/bigscience-workshop/promptsource/issues/584) would require addressing https://github.com/bigscience-workshop/promptsource/issues/725 at the same time which is a little bit involved because the state management changed! but absolutely feel free to assign yourselves!

**Comment by VictorSanh** [comment]
I just did a patch release with your fix @Guitaricet 

@awebson , also tested this new release on Colab and it seems to work smoothly!
