### ISSUE TITLE
`pip install promptsource` fails

### ISSUE THREAD

**Issue by StellaAthena** [bigscience-workshop/promptsource#728]
It looks like promptsource is not pip-installable. I get
```
(base) fsuser@recm2aejrbecoecmt:~$ pip install promptsource
ERROR: Could not find a version that satisfies the requirement promptsource (from versions: none)
ERROR: No matching distribution found for promptsource
```
when I try

**Comment by VictorSanh** [comment]
oohh, hmm, strange.
Could you say a little bit more about your setup?
Are you using Python3.7?

**Comment by StellaAthena** [comment]
No, I'm using Python 3.9.

**Comment by StellaAthena** [comment]
Okay, it worked in Python 3.7. Is there a reason why `setup.py` forbids versions beyond 3.8.0? I've been using the library [just fine](https://github.com/StellaAthena/promptsource) in Python 3.9

**Comment by VictorSanh** [comment]
Yes, we pinned to Python3.7 for various stability reasons on the interface side (https://github.com/bigscience-workshop/promptsource/issues/726#issuecomment-1039527327)
If you are not planning to use the interface, you can install from source (and remove the constraint in the `setup.py`)! Let me know if the README setup (https://github.com/bigscience-workshop/promptsource#setup) is not clear :)
