### ISSUE TITLE
Flag in Promptsource for PromptLanguage

### ISSUE THREAD

**Issue by jzf2101** [bigscience-workshop/promptsource#764]
As discussed by the evaluation meeting, it would be useful to include a flag for the language of the prompts for multi-lingual evaluation.  I wanted to open this up to see if we could allow for the creation of this additional field and to enquire as to how this would be preferred to be included. @awebson has been working with me on adding prompts into a branch and we're open to keeping this within the branch.  @stephenbach @VictorSanh do you have a preference on how this is implemented?

**Comment by stephenbach** [comment]
Closed via #771 .
