### ISSUE TITLE
Possibly incorrect prompt

### ISSUE THREAD

**Issue by xuanqing94** [bigscience-workshop/promptsource#840]
https://github.com/bigscience-workshop/promptsource/blob/40ae287a96e1675ea07d390e64182df86b9e11ea/promptsource/templates/race/high/templates.yaml#L13

options[answer] is always a correct answer. I guess you mean options[candidate] (candidate is defined a few lines before)?

**Comment by VictorSanh** [comment]
yes, good catch!
Want to open a PR to fix this?
