### ISSUE TITLE
trec templates are broken

### ISSUE THREAD

**Issue by MattYoon** [bigscience-workshop/promptsource#844]
Hello, thank you for your support!

It seems like all of trec templates produce empty input/output.
<img width="833" alt="Screenshot 2023-03-02 at 3 50 00 PM" src="https://user-images.githubusercontent.com/57797966/222361311-7298df26-84c8-419b-9649-f52c49de912f.png">

It seems like `rendered_example` contains an empty string, but I'm not quite sure what's causing this bug.
https://github.com/bigscience-workshop/promptsource/blob/71abda9468f61a6634c9a7085c130290de20534a/promptsource/templates.py#L394
Thank you in advance.

**Comment by stephenbach** [comment]
Looks like this is addressed by #832. @VictorSanh can I help with getting that merged?

**Comment by VictorSanh** [comment]
Yes #832 feel through the cracks... @MattYoon or @stephenbach if you want to/can take the torch back, please go ahead!
I am very sorry, i don't have the bandwidth to continue that in the short term :/
It's essentially about remapping the labels since the update on the dataset.

**Comment by stephenbach** [comment]
Fixed in #832.
