### ISSUE TITLE
website 

### ISSUE THREAD

**Issue by guoziting112** [bigscience-workshop/promptsource#846]
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/118614101/228444970-88a89843-4a6c-41d3-970c-0f0731a8cecc.png">

hello，here is a question，I seemly can't see the menu bar on the right side of the page.what's the reason?

**Comment by stephenbach** [comment]
Hi, I'm not sure that I understand the issue. There is not a menu on the right side in the "helicopter view." Are you trying to switch to the dataset viewer? It looks like the page hasn't loaded yet. (It can take a while the first time to collect all the data.)
